# Generated by Django 5.2 on 2025-04-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='min_quantity',
            field=models.FloatField(default=0),
        ),
    ]
